import { OpenApiAxios } from "@web-bee-ru/openapi-axios";
import type { comunService } from "./openapi-typescript"; // generated by openapi-typescript
import Axios from "axios";

const axios = Axios.create({
	baseURL: "localhost",
	adapter: "fetch",
});

const api = new OpenApiAxios<comunService.paths, "axios">(axios, { validStatus: "axios" });

const fetchEmpresa = api.get("/comun/v1/empresas/{idEmpresa}", { params: { idEmpresa: 1 } })

fetchEmpresa.then((res) => {
	console.log(res.data);
}).catch((err) => {
	console.error(err);
});


const { data, response, status } = await api.get("/comun/v1/autonomos/{idEmpresa}", { params: { idEmpresa: 1 } })